# Generated by Django 3.1.3 on 2020-12-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommers_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_cart',
            old_name='image',
            new_name='P_image',
        ),
        migrations.RenameField(
            model_name='user_cart',
            old_name='name',
            new_name='P_name',
        ),
        migrations.RenameField(
            model_name='user_cart',
            old_name='price',
            new_name='P_price',
        ),
    ]
